#!/bin/bash

SERVER=http://www.cross-copy.net

while getopts ":l" opt; do
  case $opt in
    l)
      SERVER=http://localhost:8080
      echo "using localhost instead of cross-copy.net"
      shift $((OPTIND-1)); OPTIND=1
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      shift $((OPTIND-1)); OPTIND=1
      ;;
  esac
done

if [ $# == 1 ]; then
  echo "waiting for pastes on secret '$1' on $SERVER"
  PASTE=`curl -s $SERVER/api/$1`
  [[ $PASTE == /api/${1}* ]] && PASTE=${SERVER}$PASTE
  echo $PASTE
elif [ $# == 2 ]; then
  curl -X PUT -s -d "$2" $SERVER/api/$1
else
  echo "wrong number of arguments. usage:"
  echo "   $ cross-copy secred-code              # to receive data"
  echo "   $ cross-copy secred-code 'some data'  # to send data"
fi
