//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrossCopy.AndroidClient
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int browse = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int crosscopyicon114 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int crosscopyicon144 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int crosscopyicon57 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int crosscopyicon72 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int dialog_disclosure = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int dialog_expander_ic_minimized = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int download = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int file = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int folder = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int Icon = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int remove = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int round_border = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int table_border = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int upload = 2130837518;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050000
			public const int RelativeLayout01 = 2131034112;
			
			// aapt resource value: 0x7f050013
			public const int btnChooseImage = 2131034131;
			
			// aapt resource value: 0x7f05000d
			public const int buttonGo = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int editTextSecret = 2131034124;
			
			// aapt resource value: 0x7f050004
			public const int imageButtonDel = 2131034116;
			
			// aapt resource value: 0x7f050017
			public const int listViewHistory = 2131034135;
			
			// aapt resource value: 0x7f05000f
			public const int listViewSecrets = 2131034127;
			
			// aapt resource value: 0x7f050009
			public const int tableLayout1 = 2131034121;
			
			// aapt resource value: 0x7f050011
			public const int tableRow1 = 2131034129;
			
			// aapt resource value: 0x7f050014
			public const int tableRow3 = 2131034132;
			
			// aapt resource value: 0x7f05000a
			public const int tableRowSecret = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int textView1 = 2131034123;
			
			// aapt resource value: 0x7f050012
			public const int textView5 = 2131034130;
			
			// aapt resource value: 0x7f050008
			public const int textViewDesc = 2131034120;
			
			// aapt resource value: 0x7f050006
			public const int textViewDevices = 2131034118;
			
			// aapt resource value: 0x7f050001
			public const int textViewLeft = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int textViewRight = 2131034114;
			
			// aapt resource value: 0x7f050005
			public const int textViewSecrets = 2131034117;
			
			// aapt resource value: 0x7f05000e
			public const int textViewSecretsLbl = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int textViewShare = 2131034128;
			
			// aapt resource value: 0x7f050015
			public const int textViewText = 2131034133;
			
			// aapt resource value: 0x7f050007
			public const int textViewTitle = 2131034119;
			
			// aapt resource value: 0x7f050016
			public const int textViewUpload = 2131034134;
			
			// aapt resource value: 0x7f050003
			public const int widget28 = 2131034115;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ListViewHistory = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListViewSecrets = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int MainScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Share = 2130903043;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
