// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace CrossCopy.AndroidClient
{
	
	
	public partial class Resource
	{
		
		public partial class Attribute
		{
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int dialog_disclosure = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int dialog_expander_ic_minimized = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int Icon = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int round_border = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int table_border = 2130837508;
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f05000c
			public const int buttonChoose = 2131034124;
			
			// aapt resource value: 0x7f050005
			public const int buttonGo = 2131034117;
			
			// aapt resource value: 0x7f050004
			public const int editTextSecret = 2131034116;
			
			// aapt resource value: 0x7f050010
			public const int history = 2131034128;
			
			// aapt resource value: 0x7f050007
			public const int listView1 = 2131034119;
			
			// aapt resource value: 0x7f050002
			public const int tableLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050009
			public const int tableRow1 = 2131034121;
			
			// aapt resource value: 0x7f05000d
			public const int tableRow3 = 2131034125;
			
			// aapt resource value: 0x7f050003
			public const int tableRowSecret = 2131034115;
			
			// aapt resource value: 0x7f05000a
			public const int textView1 = 2131034122;
			
			// aapt resource value: 0x7f05000b
			public const int textView5 = 2131034123;
			
			// aapt resource value: 0x7f050001
			public const int textViewDesc = 2131034113;
			
			// aapt resource value: 0x7f050006
			public const int textViewSecrets = 2131034118;
			
			// aapt resource value: 0x7f050008
			public const int textViewShare = 2131034120;
			
			// aapt resource value: 0x7f05000e
			public const int textViewText = 2131034126;
			
			// aapt resource value: 0x7f050000
			public const int textViewTitle = 2131034112;
			
			// aapt resource value: 0x7f05000f
			public const int textViewUpload = 2131034127;
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int MainScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Share = 2130903041;
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int app_name = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int hello = 2130968576;
			
			private String()
			{
			}
		}
	}
}
